### ISSUE TITLE
Bootcamp: Determine sprint 1 project details adpated to each campus/cohort

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#571]
## Projects

Following up on @CaroLaboratoria message on Slack:

> Lo primero a determinar sería la versión del reto a realizar en cada sede. Recordar que puede variar en profundidad o en temas a contener, dado que está planteado en la visión más ambiciosa posible. Esta conversación la idea es que la tengan con sus TM (y obviamente con el resto de la sede que quiera opinar). Como todos ustedes ya desarrollaron el proyecto, ya saben lo que contiene lo que es un avance gigante!

As we discussed via the Developers Chapter, the proposed mechanics for customising "projects" for each campus/cohort is something like this:

1. We start from a _shared_ version of each "project". This is proposed in collaboration between @rocioalberdi, @lalogf and @lupomontero. This _shared version_ should include a generic enough _rubric_ that we should be able to apply to all variations of the projects.
2. We solve the proposed "project" in the developers chapter in order to get informed feedback having had to work on the project _for real_ and _complete it_.
3. We adapt "project" description and boilerplate based on feedback (issues, pull requests, ...).
4. Each _local_ team makes a _copy_ of the _shared_ "project" description and boilerplate, customises it and pushes it to repo specifically created for the relevant cohort (with read permissions granted to students in that particular cohort).
5. Each _local_ team reports back (bugs, fixes, suggestions, ...), curricula maintainers lead discussions on feedback, and _shared version_ is updated with _agreed_ changes.

So far, this only affects the "project". However, each project deliverable is always accompanied by the relevant _topics_ (learning resources) and expected _performance_ against the _standard rubric_. As well as the process of publishing the content in the LMS, managing the agenda and reviewing project submissions.

## Topics (content)

On the other hand, the proposed project touches no a number of topics, and has a set of stated learning objetives: _values_, _variables_, _operators_,  _types_, _arrays_, _objects_, _flow-control_, _functions_ and _testing_. The idea is that each of these _keyword_ will link to the relevant _topic_ (be it a course, unit, read, exercise, ...).

In order to achieve this, we have been re imagining the _topics index_ and turning it into a _sort of_ library of topics. The effort here is mainly about re-organinsing existing content into a different structure, this involves moving stuff around, leaving some stuff out - very very few things, merging quite a bit of _content_ from different sources (courses), and adding a few bits and pieces to fill up some gaps. @merunga and I are leading this effort. Last night the repo went through a [massive house keeping operation in order to accommodate these changes, along with the ongoing portuguese translation](https://github.com/Laboratoria/curricula-js/issues/567).

Expect changes over the weekend as the remaining content is processed and reorganised into the new `projects` and `topics` directories.

## Rubric

All of this is happening in parallel to the development of our new _unified rubric_. In the future, rubric specific aspects of both the "project" and "topics" would be included in the description of the "project". However, in this first iteration we will have to keep an eye on this and make sure we converge by the time we get to the pre-release.

## Flight crew

In order to tackle the nuts and bolts of this process, each campus will set up a team with this specific responsibility. As far as I understand, these are the teams so far:

|       | LIM | SCL | CDMX |
-----|-----|-----|--------|
| TM | @alejandrarv | @valesmithb | @LucileBaratier  |
| JS | @RuthSalvador @Danielalab | @brecabal @nerdale | @indie-rok @Jonhks |
| UX | @Gabx04 | @bosqueinvierno | n/a |
| SS | @beatrizcf | Daniela Gaitán | Paulina Treviño |

## Milestones

* [🕐 Pre-release: 11 May 2018](https://github.com/Laboratoria/curricula-js/milestone/43)
* [🕐 Go live: 18 May 2018](https://github.com/Laboratoria/curricula-js/milestone/44)

## Next steps

Please feel free to reply with any ideas, questions, suggestions, ... and let's start creating and assigning more specific and actionable issues.

Time to rock and roll!! 🎸🚀👩‍🎤 

cc/ @diegovelezg @CaroLaboratoria @chamodev

***

PS: I'm writing this issue in english taking into consideration that we are starting to collaborate with non-spanish speakers. However, feel free to reply in Spanish or ask for clarification/translation. We are a growing community and we still need to learn how best to handle this _issue_.

**Comment by CaroLaboratoria** [comment]
Thank you @lupomontero . We decided as a team that for this Sprint, SCL and LIM are working on the UX part of the content. For the next one, CDMX is in charge.

**Comment by rocioalberdi** [comment]
Regarding soft skills, those in charge are the personal development coordinator from each training center, so they are always the same. 
For LIM Beatriz Castiglia, for CDM is Paulina Treviño and for SCL is Daniela Gaitan.

**Comment by lupomontero** [comment]
Gracias @CaroLaboratoria y @rocioalberdi por los comentarios. Acabo de actualizar los detalles del cuadro de _Flight crew_.

**Comment by lupomontero** [comment]
## Tópicos para [sprint 1](https://github.com/Laboratoria/curricula-js/milestone/43)

Un update con la lista de _tópicos_ identificados para el primer _sprint_ del Bootcamp.

En esta lista propongo una serie de _responsables_ para que nos dividamos el trabajo de _revisar_ cada uno de los temas. Verán que se trata de reorganizar y revisar contenido existente en una nueva estructura.

### Level 0

Esto son contenidos _refactorizados_ de selección, que deberían igual estar disponibles como parte del _catálogo_ de contenido:

- [ ] Browser dev tools
- [ ] [Editores de texto](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/editors)
- [ ] [HTML](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/html) @RuthSalvador @Danielalab
- [ ] [CSS](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/css) @brecabal @nerdale
- [ ] [JavaScript: Valores, tipos de datos y operadores ](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/javascript/01-basics/01-values-variables-and-types) @lupomontero
- [ ] [JavaScript: Flow control](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/javascript/02-flow-control) @indie-rok @lupomontero

### Level 1

Estos son contenidos/tópicos que se introducen por primera vez (después de selección):

- [ ] [SCM](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/scm) @indie-rok @lupomontero
- [ ] [UNIX Shell](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/shell)
- [ ] [JavaScript: Arrays](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/javascript/04-arrays) @merunga 
- [ ] [JavaScript: Objects](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/javascript/05-objects) @merunga
- [ ] [Testing](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/testing) @lupomontero

Les parece ok, la división de _tópicos_ para comenzar?

Conversemos en Slack y/o Hangouts para ver el detalle de cada _tópico_ juntxs.

**Comment by lupomontero** [comment]
Confirmo que ya se ha hecho _push_ de los detalles de evaluación (incluyendo link a rúbrica) en la descripción del proyecto:

https://github.com/Laboratoria/curricula-js/tree/v2.x/projects/01-cipher#evaluaci%C3%B3n

Porfa actualicen sus _versiones_ de los retos con estos cambios. Cualquier duda no duden en responder por acá.

**Comment by lupomontero** [comment]
Hoy queda publicado _finalmente_ todo el contenido (_tópicos_) para este primer proyecto! Todavía pueden venir algunas correcciones y modificaciones menores, pero lo importante para este proyecto está completo, ordenado y publicado en el LMS (para todos los nuevos cohorts de Bootcamp en LIM, SCL y CDMX).

Con respecto al _proyecto_ para cada sede/cohort, asumo que esto ya está solucionado/completado por cada equipo local. Cualquier duda con respecto a esto pueden responder por acá o Slack.
