### ISSUE TITLE
Project 2, details

### ISSUE THREAD

**Issue by diegovelezg** [Laboratoria/curricula-js#581]
## Project

[Data dashboard](https://github.com/Laboratoria/curricula-js/tree/v2.x/projects/02-data-dashboard)

## Topics (JS-UX-SS)

* [x] [arrays](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/javascript/04-arrays): ya publicado en LMS
* [x] [objects](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/javascript/05-objects) ya publicado en LMS
* [ ] [built-ins](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/javascript/07-built-ins): pendiente (falta agregar info, aunque sea links, sobre built-ins no cubiertos en otros lado `Math`, `Date`, `JSON`, ... , ver https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales)
* [x] [dom](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/browser/02-dom): pendiente
* [x] [xhr](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/browser/04-xhr): pendiente
* [x] [Sketching](https://github.com/Laboratoria/curricula-ux/tree/master/00-topics/02-diseno-visual/00-sketching/00-sketching) por subir al LMS
* [x] [Visual Design](https://github.com/Laboratoria/curricula-ux/tree/master/00-topics/02-diseno-visual/01-fundamentos-de-diseno-visual) por subir al LMS

## Rubric (JS-UX-SS)

* https://github.com/Laboratoria/curricula-js/blob/v2.x/projects/02-data-dashboard/README.md#evaluaci%C3%B3n
* https://docs.google.com/spreadsheets/d/e/2PACX-1vSkQy1waRpQ-16sn7VogiDTy-Fz5e7OSZSYUCiHC_bkLAKYewr4L8pWJ_BG210PeULe-TjLScNQQT_x/pubhtml#
* [x] Actualizar y publicar rúbrica de Visual Design

## Milestones

- [x] 🕐 [Project proposa: 4 May 2018](https://github.com/Laboratoria/curricula-js/milestone/45)
- [x] 🕐 [Pre-release: 25 May 2018](https://github.com/Laboratoria/curricula-js/milestone/46)
- [x] 🕐 [Go live: 1 Jun 2018](https://github.com/Laboratoria/curricula-js/milestone/47)

## Flight crew

|       | LIM | SCL | CDMX |
-----|-----|-----|--------|
| TM | @alejandrarv | @valesmithb | @LucileBaratier  |
| JS | @developerVilchez | @FabianBravoA @nadiatapm  | @AmaliaRiveraC  |
| UX | @gaposx  | n/a | @karlanavam  |
| SS | @beatrizcf | Daniela Gaitán | Paulina Treviño |

**Comment by FabianBravoA** [comment]
Yo reviso XHR

**Comment by developerVilchez** [comment]
@AmaliaRiveraC  y yo estamos revisando el DOM

**Comment by lupomontero** [comment]
@FabianBravoA, @nadiatapm: ustedes pueden ver XHR juntos?

**Comment by FabianBravoA** [comment]
Si, por supuesto!

2018-05-22 14:42 GMT-04:00 Lupo Montero <notifications@github.com>:

**Comment by diegovelezg** [comment]
Team: 
@ivandevp nos ayudó a publicar los PR pendientes relativos a tópicos pero encontró los sgtes problemas:

- DOM (@developerVilchez ) problemas con minúsculas en README. Hizo correcciones en su copia local para publicar pero se tiene que fixear igual

- xhr (@FabianBravoA ) problemas con la estructura de carpetas. Tenía como dos sub unidades y tuvo que juntar todo a lo bestia. Consecuencia: está medio desordenado el contenido en el LMS... pero está. Por favor revisar.

- built-ins (quedó dando bote la pelota y nadie la agarró) alguien se hace cargo?

**Comment by AmaliaRiveraC** [comment]
Hola @diegovelezg he intentado poner en mayúsculas el README y hacer un pull request pero me dice que no hay ningún cambio de commitear, por otro lado yo me ofrezco para apoyar en el desarrollo de built-ins, pero no sé muy bien a qué se refiere el termino, cuando lo googleo me aparecen objetos globales, si me pudieran orientar en qué tipo de información es la que estoy buscando se los agradeceré muchísimo. Saludos!

**Comment by lupomontero** [comment]
El tema de _built-ins_ queda pendiente de aprobar en este PR:

https://github.com/Laboratoria/curricula-js/pull/630

Por otro lado también está pendiente un PR con respecto a la descripción del _proyecto_:

https://github.com/Laboratoria/curricula-js/pull/628

Cierro este issue en favor de los dos PRs pendientes.
