### ISSUE TITLE
Project 3: Social network

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#632]
## Project

Ya llegamos al tercer _proyecto_ 💪

Falta actualizar el `README.md`, pero dejo el link igual acá para que lo tengamos a la mano: 
[Social Network](https://github.com/Laboratoria/curricula-js/tree/v2.x/projects/03-social-network). La versión tal cual se compartió al chapter está en [este otro repo](https://github.com/Laboratoria/social-network).

## Topics (JS-UX-SS)

Esta lista es provisional, esta semana iremos concretando qué temas/tópicos debemos incluir (de lo que ya tenemos) y que contenidos externos (links) podríamos agregar. Se agradece su feedback ahora que estamos todxs resolviendo el _proyecto_. Por ahora:

* [ ] [browser/history](#)
* [ ] [the-web-stack](#) (http, crud, ...)
* [ ] mobile first?

## Milestones

- [x] 🕐 [Project proposa: 1 Jun 2018](https://github.com/Laboratoria/curricula-js/milestone/49)
- [x] 🕐 [Pre-release: 15 Jun 2018](https://github.com/Laboratoria/curricula-js/milestone/48)
- [x] 🕐 [Go live: 22 Jun 2018](https://github.com/Laboratoria/curricula-js/milestone/50)

cc/ @Laboratoria/developers

**Comment by AnaSalazar** [comment]
En el chapter se habló de los siguientes puntos

**En la parte obligatoria:**

- [ ] Login con Firebase - Autenticación con FB, google

- [ ] Implementación con JS vanilla

- [ ] Contador de Likes

- [ ] Separación de responsabilidades

- [ ] Reordenamiento del Readme / estructura de los requerimientos

**Hacker Edition:** 

- [ ] Bibliotecas para routing

- [ ] Almacenamiento de datos con firebase o localStorage

@Laboratoria/developers

**Comment by lupomontero** [comment]
Se cierra este issue en favor de revisar #645 para futuras iteraciones del proyecto.
