### ISSUE TITLE
Stage 4: Project - Burger Queen

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#661]
I'm opening this _issue_ to follow up on progress WRT the **Burguer Queen** _project_.

## 🔧 Project

* [Burger Queen - curriculum](https://github.com/Laboratoria/curricula-js/tree/v2.x/projects/04-burger-queen): The shared repo where the design happens in the open (issues, pull requests, ...)
* [Burger Queen - DevsChapter](https://github.com/Laboratoria/burger-queen): the repo to be forked by people solving the project for the DevsChapter

## 📖 Topics

What's new in this project? Here is a list of topics that are introduced in this project for the first time in the Bootcamp roadmap.

### Find good 3rd party resources [HELP WANTED]

* [ ] offline-first / service-worker
* [ ] cloud functions
* [ ] modules
* [ ] jest

### Refactor existing curriculum content

* [x] [react](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/react) (@merunga)
* [ ] [redux](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/react/04-global-state) (@merunga)
* [ ] [angular](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/angular) (@FabianBravoA, @ivandevp)
* [ ] [webpack](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/react/02-babel-and-webpack) (@merunga)
* [ ] [babel](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/react/02-babel-and-webpack) (@merunga)
* [x] [paradigms](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/paradigms) (@lupomontero)
* [x] [functional javascript](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/functional) (@lupomontero)

## 🕐 Milestones

* [x] [Project proposal: 27 Jun 2018](https://github.com/Laboratoria/curricula-js/milestone/51)
* [x] [Pre-release: 13 Jul 2018](https://github.com/Laboratoria/curricula-js/milestone/52)
* [ ] [Go live: ?](https://github.com/Laboratoria/curricula-js/milestone/53)

## ✈️ Flight crew

This is the team assigned to "solve/complete" the project and share a model solution with the rest of the DevsChapter.

* @FabianBravoA
* @espinozasenior 
* @lizzie136  

cc/ @Laboratoria/developers

**Comment by diegovelezg** [comment]
Algunas preguntas/observaciones:
- "ver pedidos" es lo que verían en la cocina ?
- ¿Esperamos que ellas descubran y hagan todo el flujo completo de uso? A mí me gusta (mesero: pedido, cocina:recibe pedido y marca como listo, mesero: cerrar la cuenta como pagada, etc.)
- No me gusta que seamos tan explícitos en los botones grandes de la UI, es algo que yo esperaría descubran por UX @lalogf ?

**Comment by gaposx** [comment]
> @diegovelezg: No me gusta que seamos tan explícitos en los botones grandes de la UI, es algo que yo esperaría descubran por UX @lalogf ?

+1
Es algo que deberían descubrir al momento de hacer benchmarking y conocer a su usuario.

**Comment by lupomontero** [comment]
Ver: http://community.laboratoria.la/t/track-fe-propuestas-cambio-de-proyecto/671

@diegovelezg: flight crew actualizado... (he incluido a @espinozasenior y @lizzie136)

**Comment by lizzie136** [comment]
Aún estoy trabajando en la base de React, este es el link del repositorio https://github.com/Laboratoria/2018-1-BurgerQueen-React

**Comment by lupomontero** [comment]
Ver PR con propuesta presentada hoy: https://github.com/Laboratoria/curricula-js/pull/719

Imlpementación modelo (React): https://github.com/lupomontero/burger-queen/tree/develop (wip)

Repo para que el chapter resuelva el proyecto: https://github.com/Laboratoria/burger-queen

**Comment by lupomontero** [comment]
Se cierra este issue por ahora... abramos nuevos issues más específicos si surge alguna cosa retocar.
