### ISSUE TITLE
Stage 4: Project - Markdown links

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curricula-js#662]
I'm opening this _issue_ to follow up on progress WRT the **Markdown Links** _project_.

## 🔧 Project

* [Markdown links - curriculum](https://github.com/Laboratoria/curricula-js/tree/v2.x/projects/04-md-links): The shared repo where the design happens in the open (issues, pull requests, ...)
* [Markdown links - DevsChapter](https://github.com/Laboratoria/md-links): the repo to be forked by people solving the project for the DevsChapter

## 📖 Topics

What's new in this project? Here is a list of topics that are introduced in this project for the first time in the Bootcamp roadmap.

### Find good 3rd party resources [HELP WANTED]

* [x] modules
* [x] jest
* [x] Node.js (process, filesystem, http, ...)

### Refactor existing curriculum content

* [x] [paradigms](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/paradigms) (@lupomontero)
* [x] [functional javascript](https://github.com/Laboratoria/curricula-js/tree/v2.x/topics/functional) (@lupomontero)

## 🕐 Milestones

* [x] [Project proposal: 27 Jun 2018](https://github.com/Laboratoria/curricula-js/milestone/51)
* [x] [Pre-release: 13 Jul 2018](https://github.com/Laboratoria/curricula-js/milestone/52)
* [x] [Go live: 20 Jul 2018](https://github.com/Laboratoria/curricula-js/milestone/53)

## ✈️ Flight crew

This is the team assigned to "solve/complete" the project and share a model solution with the rest of the DevsChapter.

* @lupomontero
* @brecabal 
* @MaiaRojas 

cc/ @Laboratoria/developers

**Comment by MaiaRojas** [comment]
Hola, como no nos  vamos a organizar para el desarrollo del proyecto. :sweat_smile:

**Comment by lupomontero** [comment]
Ver PRs: #680, #681 y #682

**Comment by lupomontero** [comment]
Ver: #684
